Capistrano::Configuration.instance(:must_exist).load do
  namespace :sass do
    desc 'Updates the stylesheets generated by Sass'
    task :update, :roles => :app do
      invoke_command "cd #{latest_release}; RAILS_ENV=#{rails_env} rake sass:update"
    end
  end
end